name: check-commit

on:
  - push
  - pull_request

jobs:
  check-commit:
    runs-on: macos-15

    steps:
      - name: Use Xcode 16.4
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Current platform versions
        run: |
          sw_vers
          xcodebuild -version
          swift --version
          swiftlint version

      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Run lint
        run: |
          make lint

      - name: Run test
        run: |
          make test TEST_DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5"

      - name: Run doc
        run: |
          make doc
